- name: Install required PHP modules
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000
  with_items:
    - php-xml
    - php-zip

- name: Download LDAP Account Manager (LAM)
  get_url: >
    url=http://sourceforge.net/projects/lam/files/LAM/6.3/ldap-account-manager_6.3-1_all.deb
    dest=/opt

- name: Install LAM 6.3
  command: dpkg -i ldap-account-manager_6.3-1_all.deb chdir=/opt
